# permissions for end users to edit pvcextensions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: pvcextension-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: db-operator
    app.kubernetes.io/part-of: db-operator
    app.kubernetes.io/managed-by: kustomize
  name: pvcextension-editor-role
rules:
- apiGroups:
  - gauravkr19.dev
  resources:
  - pvcextensions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gauravkr19.dev
  resources:
  - pvcextensions/status
  verbs:
  - get
